"""
Django settings for itapps project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '030415')

WEBSITE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME', None) 
DEBUG = WEBSITE_HOSTNAME == None


if DEBUG: 

    ALLOWED_HOSTS = [] 

else: 

    ALLOWED_HOSTS = [WEBSITE_HOSTNAME] 

    CSRF_TRUSTED_ORIGINS = [f'https://{WEBSITE_HOSTNAME}']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'itreporting', 
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itapps.wsgi.application'

print("======= DJANGO DATABASE SETTINGS =======")
print("ENGINE:", 'django.db.backends.mysql')
print("NAME:", os.getenv('AZURE_DB_NAME'))
print("USER:", os.getenv('AZURE_DB_USER'))
print("PASSWORD:", os.getenv('AZURE_DB_PASSWORD'))  # Remove before deploying!
print("HOST:", os.getenv('AZURE_DB_HOST'))
print("PORT:", os.getenv('AZURE_DB_PORT', '3306'))
print("========================================")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('AZURE_DB_NAME'),
        'USER': os.getenv('AZURE_DB_USER'),
        'PASSWORD': os.getenv('AZURE_DB_PASSWORD'),
        'HOST': os.getenv('AZURE_DB_HOST'),
        'PORT': os.getenv('AZURE_DB_PORT', '3306'),
        'OPTIONS': {
            'ssl': {
                'ca': '/etc/ssl/certs/ca-certificates.crt'
            }
        }
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/' (OLD STATIC)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_REDIRECT_URL = 'itreporting:home'
LOGIN_URL = 'login' #Repalced with the line 134 below 
#MEDIA_ROOT = BASE_DIR / 'media' (OLD)
#MEDIA_URL = '/media/' (OLD)
LOGIN_URL = 'itreporting:home'

AZURE_SA_NAME = os.environ['AZURE_SA_NAME']
AZURE_SA_KEY = os.environ['AZURE_SA_KEY']

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_SA_NAME,
            "account_key": AZURE_SA_KEY,
            "azure_container": "media",
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_SA_NAME,
            "account_key": AZURE_SA_KEY,
            "azure_container": "static",
        },
    },
}

STATIC_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/static/'

MEDIA_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/media/'
