"""
Django settings for itapps project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '030415')

WEBSITE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME', None) 

# Check if we're in Azure (production) by checking for Azure-specific environment variables
# Azure sets WEBSITE_HOSTNAME automatically, but we can also check for other Azure vars
IN_AZURE = bool(os.environ.get('AZURE_DB_NAME') or os.environ.get('WEBSITE_HOSTNAME'))
DEBUG = not IN_AZURE

if DEBUG: 
    ALLOWED_HOSTS = [] 
else: 
    # Allow Azure domains - works even if WEBSITE_HOSTNAME is not explicitly set
    ALLOWED_HOSTS = [
        '.azurewebsites.net',  # Allow all Azure Web App domains
        'c2027394-cgaraaddfugnb5ce.uksouth-01.azurewebsites.net',  # Your specific domain
    ]
    
    # Add WEBSITE_HOSTNAME if it exists
    if WEBSITE_HOSTNAME:
        ALLOWED_HOSTS.append(WEBSITE_HOSTNAME)
    
    CSRF_TRUSTED_ORIGINS = [
        'https://*.azurewebsites.net',
        'https://c2027394-cgaraaddfugnb5ce.uksouth-01.azurewebsites.net',
    ]
    
    # Add WEBSITE_HOSTNAME to CSRF if it exists
    if WEBSITE_HOSTNAME:
        CSRF_TRUSTED_ORIGINS.append(f'https://{WEBSITE_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'itreporting', 
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'itreporting.context_processors.news_feed',
            ],
        },
    },
]

WSGI_APPLICATION = 'itapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use Azure MySQL if environment variables are set, otherwise use SQLite for local development
if 'AZURE_DB_NAME' in os.environ:
    DATABASES = { 
        'default': { 
            'ENGINE': 'django.db.backends.mysql', 
            'NAME': os.environ['AZURE_DB_NAME'], 
            'HOST': os.environ['AZURE_DB_HOST'], 
            'PORT': os.environ['AZURE_DB_PORT'], 
            'USER': os.environ['AZURE_DB_USER'], 
            'PASSWORD': os.environ['AZURE_DB_PASSWORD'], 
            'OPTIONS': {
                'ssl': {
                    'ca': '/etc/ssl/certs/ca-certificates.crt',
                },
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'  # Changed to UK timezone

USE_I18N = True

USE_TZ = True

# Cache configuration for weather API
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/' (OLD STATIC)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_REDIRECT_URL = 'itreporting:home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'itreporting:home'

# Use Azure Storage if environment variables are set, otherwise use local file storage
if 'AZURE_SA_NAME' in os.environ and 'AZURE_SA_KEY' in os.environ:
    AZURE_SA_NAME = os.environ['AZURE_SA_NAME']
    AZURE_SA_KEY = os.environ['AZURE_SA_KEY']

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": AZURE_SA_NAME,
                "account_key": AZURE_SA_KEY,
                "azure_container": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": AZURE_SA_NAME,
                "account_key": AZURE_SA_KEY,
                "azure_container": "static",
            },
        },
    }

    STATIC_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/static/'
    MEDIA_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/media/'
else:
    # Local file storage
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'

# OpenWeatherMap API Key
OPENWEATHER_API_KEY = os.environ.get('OPENWEATHER_API_KEY')

# Email Configuration
# If SMTP credentials are provided, use SMTP backend (for real emails)
# Otherwise, use console backend (emails printed to console) in development
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Use SMTP backend when credentials are provided
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
else:
    # Use console backend in development (emails printed to console/terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default email address for sending emails
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@studentitservices.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Site domain for password reset links
# In development, use localhost. In production, use your actual domain
if DEBUG:
    # For local development
    SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'localhost:8000')
    SITE_PROTOCOL = 'http'
else:
    # For production
    SITE_DOMAIN = os.environ.get('SITE_DOMAIN', WEBSITE_HOSTNAME or 'yourdomain.com')
    SITE_PROTOCOL = 'https'
