# Generated by Django 5.2.7 on 2025-12-12 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('itreporting', '0002_rename_date_submited_issue_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the module', max_length=200)),
                ('code', models.CharField(help_text='Module code (e.g., CS101)', max_length=20, unique=True)),
                ('credit', models.PositiveIntegerField(help_text='Number of credits')),
                ('category', models.CharField(choices=[('Core', 'Core'), ('Optional', 'Optional'), ('Elective', 'Elective'), ('Foundation', 'Foundation')], help_text='Module category', max_length=50)),
                ('description', models.TextField(help_text='Module description')),
                ('availability', models.CharField(choices=[('open', 'Open for Registration'), ('closed', 'Closed for Registration')], default='open', help_text='Registration availability status', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses_allowed', models.ManyToManyField(blank=True, help_text='Courses (Groups) allowed to register for this module', related_name='modules', to='auth.group')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
    ]
